language: python
python:
  - 3.7
os: linux
dist: xenial
cache: pip
services:
  - docker
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.26.2
    - DEPENDENCIES=jackgreenberg/tools-dependencies
    - BACKEND=jackgreenberg/tools-backend
    - secure: znfGbnNjQhqc309T9mBfrLYvXPgPkydW6f0zH03e83nQKtIbs56vX1gpOlbXtgVQRewRF7HBUlWBEilC1TQVu0dxmT45KP+aBdoiCOHq+c4Z+nOqq+UPql0HgF3vOgmxQA8ilbU5TAUt+2D80deFCTVdPOuhs6GtKFKUzmjZGMMbr12z9tU6DhSsumD4keplmGCMaLEpz9IzCcA1KIJ/pkvpK/rO0aT4BvKTDOLbz/QkdCfsTFFStqr6Ztt1hHszOOtwhRIFQa/C5xGmqDSP/vn9Vl2PEAV8+zdh3BHpbo0ci+Vp/OZdsPXC27x2wm248j9wLM5mnAXlsqFpyC34Xf/xCBo+cPoIq8KCxalX6C1zImiDhTO4266+xnOFXCzEhKsV9IEcdE71nroXP9zmmm/RiAyGKkwn/Ppas2R9MF3hPp6af8iSMcRQ/X11xD9iigtTG1+y8b+BFGC2E+VnRZMMdg/OZuBHUweuCAwNpOrBIdnfekaczO/65bLi6nAqSZMwEiipVekYWF9Zid2tNaHJXYUrUb8VwHWfQiwPyoyrCDuVKVuR6t30B85uEV+bUqTAO/IH+5BtARZOo52a+6Bbi2k+V4+kBnkltlz9xpGsUon3dLYYDUWp5ksSS1e/o3QW9fbUQ/xO1Z88ElByyQA0A6rDbDlrJo57TRVYAfc=
    - secure: tahevMWpxW/EToVtGFNE9xiG9MVAujjiPQDaSWIZRwRPamksDz/RYsFh7SrXySuy9a5VvdXrZmUX3fgCr+UAKBg8Cjdq+R8TY0mgOTUtdRCQjc1/pHjkBhGOAtL9McizHquYypvNo9Zztswe1Z3zFBNSmUKwADg3OQ1vrq6U/zXHQbq7JWWFxPPKzdBe9IeGESrjKoH5CM/0orZdqfhCayEShFMVO27qC3WJia6GPx8OoGSRtUmdY+lwvHIvqSoe5om2w3juR0eIac80fRMwrDuml8jtee5naLqY25TGxECxfVT8mBILBT4PLXn34lxXWjBQplKdKJ7giiuwfgR8ik8W2GTI1ev0f4+Uw5pTUK9DLkRU0Y8TpKAAjLJtDHwQn5cd5hyup3miarR5latgMoHnX+OR1vZvjDK49Dt5ZKnb5ABA1DBZToJN/okQ4iI/kQMB6gRQHhlgZa4iOHKC1QfeVGKdmmwfPNYRd+EPOOx/vhJEDttm0Aehx5Kyy1i2dowaCw2zOlGBSsXPduKNo1dtGqr0b315zkmM54AsRvpm4/ejAn7dOg5NKztV5h08b5Za1hO2DFjWxwzgnumzgBZFtK/KeZ8xmmnumKQJfYZ0wiDhXedx+NkgLHbSd3NSbjYSJwDy4B6NqstJbysoGWrW/h3ceqMdD0I2SoPb6tI=

# Install docker-compose version
before_install:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version

# Build docker containers
install:
  - docker pull ${DEPENDENCIES} || true
  - docker build --pull -t ${DEPENDENCIES} --cache-from ${DEPENDENCIES} --target=dependencies .
  - docker build --tag ${BACKEND} --cache-from ${DEPENDENCIES} --cache-from ${BACKEND} .

# Run the containers with docker-compose
before_script:
  - docker-compose up -d
  - docker-compose ps

# Run tests and lints
script:
  - docker exec -ti -e CODECOV_TOKEN=${CODECOV_TOKEN} tools-backend nox -s lint safety tests coverage

# Spin down docker containers
after_script:
  - docker-compose down

after_success:
  - echo "$DOCKER_PASS" | docker login -u jackgreenberg --password-stdin
  - docker tag $DEPENDENCIES:latest $DEPENDENCIES:$TRAVIS_BRANCH
  - docker tag $DEPENDENCIES:latest $DEPENDENCIES:$TRAVIS_BUILD_NUMBER
  - docker push $DEPENDENCIES:latest
  - docker push $DEPENDENCIES:$TRAVIS_BRANCH
  - docker push $DEPENDENCIES:$TRAVIS_BUILD_NUMBER

notifications:
  webhooks:
    - https://fathomless-fjord-24024.herokuapp.com/notify
