language: python
python:
  - 3.7
services:
  - docker
before_install:
  - docker build -t tools .
install:
  - poetry install

jobs:
  include:
    - stage: lint
      script: flake8 .
    - stage: test
      script: pytest
