language: python
python:
  - 3.7
services:
  - docker
before_install:
  - docker build -t jgreenberg/tools .
  # - docker run --rm
install:
  - poetry install

jobs:
  include:
    - stage: test
      script: nox
