language: python
python:
  - 3.7
services:
  - docker
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.26.2
    - IMAGE_NAME=jackgreenberg/tools
    - BASE_IMAGE=jackgreenberg/poetry:latest
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
  - docker pull ${BASE_IMAGE}
  - docker build -t ${IMAGE_NAME} .
  - docker images
  - docker-compose up -d
  - docker ps

install:
  - docker exec -ti tools-backend /bin/bash -c "pip3 install pytest"

script:
  - docker exec -ti tools-backend /tools/scripts/testing.sh

after_script:
  - docker-compose down
