language: python
python:
  - 3.7
os: linux
dist: xenial
cache: pip
services:
  - docker
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.26.2
    - DEPENDENCIES=jackgreenberg/tools-dependencies
    - BACKEND=jackgreenberg/tools-backend
    - secure: hCBw+brUJGBrwQWN9Ac77T1TAmadeygVjIKTpBPuB9i/WgxDCPEFipGz7CVarEUrX0bQWhoH4w0nNAmpbpayw/lcgE6fUFAKUcz+AIOKxDKyilZ8xa2FFxjp3bPYl4fpW03R0Q5q2MoyhIAI4lDt2azuVqkWdnO4wDll4ltazr2qQ0fVE4GZn2RlJwphuwC9bpSkpDH4/AWbNivBBXbW0O4AEoBGRh9oAohoeVAVhVIJ90hyccIcfhlRUjreZKG1SxWUUDvlIwRrcrOEJEt/ntyoprpqwkw0h3MuqthgXnrCyv8Q8v2WZoXlEeEqm1dsNCb73gcxZj461XUYngub5zWNUPBvWedBB838ei7RTx8fl7gj0OtDXZDkqJflMg3sEIIdyQvskFkd5zcrNZWIdcDrD4cvL/AQQ0tlbbX8/cmJQla6VpmYzjv1IfllQTFF1m5KYxeQ3UJ3hs1Yw8qqCzUBGT+JcfhFIyQyozuisQA4aAOhbZNBDOwCtPKOrNoznQIwlrk/BWU9beoQ8eFcqaio6jJB6snQbrfpEjaCnqGzTkLuYGRkL/lFhGy6/20JVG9anbcPxrgXKEHcQKrMxVmceku/f8OyD+olIV5Zcj0wLOxAFB1uO8dvfqowkvAiZA+O3SgICUwhrHU70DNkN1SV4Gi66cD7GBp+dOAwzK8=
    - secure: znfGbnNjQhqc309T9mBfrLYvXPgPkydW6f0zH03e83nQKtIbs56vX1gpOlbXtgVQRewRF7HBUlWBEilC1TQVu0dxmT45KP+aBdoiCOHq+c4Z+nOqq+UPql0HgF3vOgmxQA8ilbU5TAUt+2D80deFCTVdPOuhs6GtKFKUzmjZGMMbr12z9tU6DhSsumD4keplmGCMaLEpz9IzCcA1KIJ/pkvpK/rO0aT4BvKTDOLbz/QkdCfsTFFStqr6Ztt1hHszOOtwhRIFQa/C5xGmqDSP/vn9Vl2PEAV8+zdh3BHpbo0ci+Vp/OZdsPXC27x2wm248j9wLM5mnAXlsqFpyC34Xf/xCBo+cPoIq8KCxalX6C1zImiDhTO4266+xnOFXCzEhKsV9IEcdE71nroXP9zmmm/RiAyGKkwn/Ppas2R9MF3hPp6af8iSMcRQ/X11xD9iigtTG1+y8b+BFGC2E+VnRZMMdg/OZuBHUweuCAwNpOrBIdnfekaczO/65bLi6nAqSZMwEiipVekYWF9Zid2tNaHJXYUrUb8VwHWfQiwPyoyrCDuVKVuR6t30B85uEV+bUqTAO/IH+5BtARZOo52a+6Bbi2k+V4+kBnkltlz9xpGsUon3dLYYDUWp5ksSS1e/o3QW9fbUQ/xO1Z88ElByyQA0A6rDbDlrJo57TRVYAfc=

# Install docker-compose version
before_install:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version

# Build docker containers
install:
  - docker pull ${DEPENDENCIES} || true
  - docker build --pull -t ${DEPENDENCIES} --cache-from ${DEPENDENCIES} --target=dependencies .
  - docker build --pull -t ${BACKEND} --cache-from ${DEPENDENCIES} --cache-from ${BACKEND} .

# Run the containers with docker-compose
before_script:
  - docker-compose up -d
  - docker-compose ps

# Run tests and lints
script:
  - docker exec -ti -e CODECOV_TOKEN=${CODECOV_TOKEN} tools-backend nox -s lint safety tests coverage

# Spin down docker containers
after_script:
  - docker-compose down

notifications:
  webhooks:
    - https://fathomless-fjord-24024.herokuapp.com/notify
