language: python
python:
  - 3.7
services:
  - docker
env:
  global:
    - IMAGE_NAME=jackgreenberg/tools
    - BASE_IMAGE=jackgreenberg/poetry:latest
before_install:
  - docker pull ${BASE_IMAGE}
  - docker build -t ${IMAGE_NAME} .
  - docker images
  - docker-compose up -d
  - docker run ${IMAGE_NAME} /bin/bash "cd /tools; nox"

script:
  - nox
