version: "3.8"
services:
  tools-backend:
    build:
      context: .
    image: jackgreenberg/tools-backend:latest
    container_name: tools-backend
    restart: always
    environment:
      FLASK_SKIP_DOTENV: 1
      AZURE_APPLICATION_ID: ${AZURE_APPLICATION_ID}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
    ports:
      - "8000:5000"
    volumes:
      - .:/tools
    networks:
      - tools-net

  tools-db:
    container_name: tools-db
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_DB: tools
      POSTGRES_USER: tools
      POSTGRES_PASSWORD: development
    volumes:
      - tools-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - tools-net

  tools-proxy:
    container_name: tools-proxy
    build:
      context: ./deployment
      dockerfile: Dockerfile.nginx
    image: jackgreenberg/tools-proxy:latest
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks:
      - tools-net
    depends_on:
      - tools-backend

  # letsencrypt:
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   container_name: tools-letsencrypt
  #   volumes_from:
  #     - nginx-proxy
  #   volumes:
  #     - tools-certs:/etc/nginx/certs:rw
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   network_mode: bridge

networks:
  tools-net:
    name: tools-net

volumes:
  tools-data:
    name: tools-data
  # tools-certs:
