"""Update tables

Revision ID: 15a34a63be96
Revises: a751aa6d5ea5
Create Date: 2020-07-23 16:11:48.175302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a34a63be96'
down_revision = 'a751aa6d5ea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
