"""add user id

Revision ID: e632be55513f
Revises: 240afa40c7bd
Create Date: 2020-07-28 04:02:56.822889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e632be55513f"
down_revision = "240afa40c7bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_training",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("training_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["training_id"], ["training.id"],),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("user_role")
    op.add_column("training", sa.Column("tool_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "training", "tool", ["tool_id"], ["id"])
    op.add_column(
        "user", sa.Column("display_name", sa.String(length=255), nullable=True)
    )
    op.alter_column("user", "user_id", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("user", "name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.alter_column("user", "user_id", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("user", "display_name")
    op.drop_column("training", "tool_id")
    op.create_table(
        "user_role",
        sa.Column("user_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("user_id", name="user_role_pkey"),
    )
    op.drop_table("user_training")
    # ### end Alembic commands ###
